language: R
dist: trusty  # ubuntu 14.04 has additional libraries available
sudo: required
cache: packages
warnings_are_errors: false

# install debian libraries to match R-servers
# update pre-installed packages to latest versions
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libgdal-dev libproj-dev python-protobuf libprotoc-dev libprotobuf-dev libv8-dev librsvg2-dev

# last stable version of devtools does not support private depositories
r_github_packages: hadley/devtools#1263

script:
  - R CMD build --no-manual --no-build-vignettes --no-resave-data .
  - R CMD check --as-cran --no-manual --no-build-vignettes --no-tests *.tar.gz
  - sudo Rscript -e 'install.packages("roxygen2")'
  - if [ -d tests/testthat ]; then Rscript -e 'library(methods); res<-devtools::test(); df <- as.data.frame(res); pass <- sum(df$failed)==0 && all(!df$error); quit(status=1-pass, save="no")'; fi

notifications:
  slack:
    rooms:
      - numbers:FTgSTNHC2rpanhJMGTKMwZXM#github-notifications
    template:
      - "Build <%{build_url}|#%{build_number}> %{result} in %{repository_name}@%{branch} by %{author}: <%{compare_url}|%{commit_message}>"
    on_success: change
    on_failure: always

after_success: >-
  if [ $TRAVIS_EVENT_TYPE == 'push' ] ; then
    Rscript -e 'require(devtools); install_github("NumbersInternational/travisCI"); travisCI::TriggerDownstreamBuilds()';
  fi
