# context("LineChart")
#  rm(list=ls())

# make.table <- function(x, y, label = "Series", row = TRUE)
# {
#     output <- table(x,y)
#     if (row)
#         rownames(output) <- paste("Series", 1:length(x))
#     else
#         colnames(output) <- paste("Series", 1:length(y))
#
#     output
# }
#
# x.data = c("A","B","C","D","E")
# y.data = c(1, 2, 3, 4, 5)
# var1 <- c(1, 2, 3, 4, 5)
# var2 <- c(5, 4, 3, 2, 1)
# var3 <- c(3, 3, 3, 3, 3)
# var4 <- c(3, 4, 5, 2, 1)
# var5 <- c(5, 4, 2, 3, 1)
# alpha.five <- LETTERS[1:5]
# logic.vector <- c(TRUE, FALSE, TRUE, TRUE, FALSE)
# logic.vector.named <- c(A = TRUE, B = FALSE, C = TRUE, D = TRUE, E = FALSE)
# named.vector.a <- c("A" = 1, "B" = 2, "C" = 3)
# named.vector.b <- c("D" = 3, "E" = 2, "F" = 1)
# factor.a <- factor(x.data)
# factor.b <- factor(y.data)
# x.dates <- c(1440236400000,1450236400000,1460236400000,1470236400000,1480236400000)
# x.dates <- as.POSIXct(x.dates/1000, origin = "1970-01-01")
#
# ################### Test Line Chart outputs for various data formats.
#
# good.examples <- list("A named vector becomes a ChartMatrix" = list(Y = c("A" = 1, "B" = 2, "C" = 3, "D" = 4, "E" = 5), X = NULL, transpose = FALSE),
#                       "A single column table becomes a chart matrix" = list(X = NULL, Y = make.table(x.data, var3), transpose = FALSE),
#                       "A numeric matrix with one column becomes a chart matrix" = list(X = NULL, Y = matrix(1:5, ncol = 1, dimnames = list(x = LETTERS[1:5], series = "Series 1")), transpose = FALSE),
#                       "A table with one row becomes a chart matrix" = list(X = NULL, Y = make.table(var3, x.data, row = FALSE), transpose = TRUE),
#                       "One numeric or integer vector and one character vector become a chart matrix" = list(X = x.data, Y = y.data, transpose = FALSE),
#                       "One numeric or integer vector and one factor vector become a chart matrix" = list(Y = y.data, X = factor(x.data), transpose = FALSE),
#                       "One numeric or integer vector and one ordered factor vector become a chart matrix" = list(Y = y.data, X = as.ordered(x.data), transpose = FALSE),
#                       "One or more numeric or integer vector(s) in a list and one character vector become a chart matrix" = list(Y = list(A = var1, B = var1, C = var1, D = var1, E = var1), X = alpha.five, transpose = FALSE),
#                       "One or more numeric or integer vector(s) in a data frame and one character vector become a chart matrix" = list(Y = cbind(var1, var1, var1, var1, var1), X = alpha.five, transpose = FALSE),
#                       "One or more factors with the same levels in a data frame become a chart matrix" = list(X = factor.a, Y = factor.a, transpose = FALSE),
#                       "One numeric or integer variable and one date variable become a chart matrix" = list(Y = var1, X = x.dates, transpose = TRUE))

# for (i in 1:length(good.examples))
# {
#     print(LineChart(y = good.examples[[i]]$Y, x = good.examples[[i]]$X, type = "Line", transpose = good.examples[[i]]$transpose, title = names(good.examples)[i]))
#
#     # cat(paste("Press [enter] to continue (test ", i, "/", length(good.examples), ").", sep = ""))
#     # line <- readline()
# }
#
# ################### Test Area Chart outputs for various layout formats.
# context("LineChart Layout")
#
# ### Data
# basic.style.data <- rbind(c(0.2,0.3,0.3,0.5,0.3,0.6,0.4,0.8,0.2,0.5,0.1,0.3),c(0.3,0.5,0.1,0.3,0.1,0.2,0.1,0.4,0.1,0.2,0.1,0.4))
# rownames(basic.style.data) <- c("Series1","Series2")
# colnames(basic.style.data) <- c("Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec")
# basic.style.colors <- c(rgb(31,78,121, max=255), rgb(192,0,0, max=255))
# basic.style.line.colors <- c(rgb(31,78,121, max=255),rgb(192,0,0, max=255))
#
#
# junk.data <- read.csv("C:\\R\\junk.csv", header = TRUE)
# junk.data.text <- as.matrix((junk.data[, -1, drop = FALSE]))
# rownames(junk.data) <- junk.data[, 1]
# junk.data <- as.matrix(junk.data[, -1])
# junk.colors <- c(grDevices::rgb(219, 99, 24, 255, maxColorValue = 255), # Apples, orange-ish.
#                  grDevices::rgb(13, 168, 170, 255, maxColorValue = 255), # Bananas, teal.
#                  grDevices::rgb(110, 18, 90, 255, maxColorValue = 255), # Lemons, dark purple
#                  grDevices::rgb(21, 113, 189, 255, maxColorValue = 255), # Limes, blue
#                  grDevices::rgb(97, 111, 2, 255, maxColorValue = 255), # Oranges, dark green
#                  grDevices::rgb(8, 68, 111, 255, maxColorValue = 255), # Pears, dark blue
#                  grDevices::rgb(175, 21, 1, 255, maxColorValue = 255), # Strawberries, dark red
#                  grDevices::rgb(158, 72, 14, 255, maxColorValue = 255), # Gooseberries
#                  grDevices::rgb(99, 99, 99, 255, maxColorValue = 255), # Cloudberries
#                  grDevices::rgb(153, 115, 0, 255, maxColorValue = 255), # Kiwi fruit
#                  grDevices::rgb(38, 68, 120, 255, maxColorValue = 255), # Raspberries
#                  grDevices::rgb(67, 104, 43, 255, maxColorValue = 255), # Blackberries
#                  grDevices::rgb(124, 175, 221, 255, maxColorValue = 255), # Currants
#                  grDevices::rgb(241, 151, 90, 255, maxColorValue = 255), # Rhubarb
#                  grDevices::rgb(183, 183, 183, 255, maxColorValue = 255), # Peach
#                  grDevices::rgb(255, 205, 51, 255, maxColorValue = 255), # Mango
#                  grDevices::rgb(105, 142, 208, 255, maxColorValue = 255), # Papaya
#                  grDevices::rgb(140, 193, 104, 255, maxColorValue = 255), # Goat
#                  grDevices::rgb(50, 125, 194, 255, maxColorValue = 255), # Blueberries
#                  grDevices::rgb(210, 96, 18, 255, maxColorValue = 255)) # Lingonberries
#
#
#
#
#
#
#
# clean.style.data <- rbind(c(0.841470985,0.89120736,0.932039086,0.963558185,0.98544973,0.997494987,0.999573603,0.99166481,0.973847631,0.946300088,0.909297427,0.863209367,0.808496404,0.745705212,0.675463181,0.598472144,0.515501372,0.42737988,0.33498815,0.239249329,0.141120008,0.041580662,0.058374143,0.157745694,0.255541102,0.350783228,0.442520443,0.529836141,0.611857891,0.687766159,0.756802495,0.818277111,0.871575772,0.916165937,0.951602074,0.977530118,0.993691004,0.999923258,0.996164609,0.982452613,0.958924275,0.925814682,0.883454656,0.832267442,0.772764488,0.705540326,0.631266638,0.550685543,0.464602179,0.373876665,0.279415498,0.182162504,0.083089403,0.0168139,0.116549205,0.215119988,0.311541364,0.404849921,0.494113351,0.578439764,0.656986599,0.72896904,0.793667864,0.850436621,0.898708096,0.937999977,0.967919672,0.988168234,0.998543345,0.998941342,0.989358247,0.969889811,0.940730557,0.902171834,0.854598908,0.798487113,0.734397098),
#                           c(0.540302306,0.453596121,0.362357754,0.267498829,0.169967143,0.070737202,0.029199522,0.128844494,0.227202095,0.323289567,0.416146837,0.504846105,0.588501117,0.666276021,0.737393716,0.801143616,0.856888753,0.904072142,0.942222341,0.970958165,0.989992497,0.99913515,0.998294776,0.98747977,0.966798193,0.936456687,0.896758416,0.848100032,0.790967712,0.725932304,0.653643621,0.574823947,0.490260821,0.400799172,0.30733287,0.210795799,0.112152527,0.012388663,0.087498983,0.186512369,0.283662185,0.377977743,0.468516671,0.554374336,0.634692876,0.708669774,0.775565879,0.834712785,0.885519517,0.927478431,0.960170287,0.983268438,0.996542097,0.999858636,0.993184919,0.976587626,0.950232592,0.914383148,0.86939749,0.8157251,0.753902254,0.684546666,0.608351315,0.526077517,0.438547328,0.346635318,0.251259843,0.153373862,0.053955421,0.046002126,0.145500034,0.243544154,0.339154861,0.431376845,0.519288654,0.602011903,0.678720047),
#                           c(0.324921345,0.279916494,0.227856881,0.170456593,0.109251961,0.045678943,0.018870567,0.083017584,0.145378206,0.204540087,0.259017159,0.307179239,0.347172513,0.37686789,0.393889282,0.395774144,0.380296607,0.345936803,0.29241662,0.221162939,0.135533951,0.040677919,0.057009965,0.150737164,0.234264983,0.302718644,0.353065915,0.38419087,0.396616833,0.392019506,0.372694029,0.341106472,0.299598458,0.250251887,0.194878007,0.135077103,0.072318523,0.008007389,0.056474473,0.11974729,0.180414543,0.237028067,0.288027375,0.331660601,0.365915574,0.388508069,0.396981824,0.38896283,0.362573713,0.316955771,0.252782003,0.172601307,0.08086104,0.016472917,0.112658058,0.201113541,0.276317022,0.334437658,0.373578553,0.393632114,0.395860367,0.382362426,0.355578701,0.317927724,0.27160674,0.218535104,0.160391304,0.098689763,0.03485583,0.029722376,0.093666196,0.155589031,0.214070037,0.267604404,0.314529716,0.352948003,0.380683664))
# colnames(clean.style.data) <- c("Jan-10","Feb-10","Mar-10","Apr-10","May-10","Jun-10","Jul-10","Aug-10","Sep-10","Oct-10","Nov-10","Dec-10","Jan-11","Feb-11","Mar-11","Apr-11","May-11","Jun-11","Jul-11","Aug-11","Sep-11","Oct-11","Nov-11","Dec-11","Jan-12","Feb-12","Mar-12","Apr-12","May-12","Jun-12","Jul-12","Aug-12","Sep-12","Oct-12","Nov-12","Dec-12","Jan-13","Feb-13","Mar-13","Apr-13","May-13","Jun-13","Jul-13","Aug-13","Sep-13","Oct-13","Nov-13","Dec-13","Jan-14","Feb-14","Mar-14","Apr-14","May-14","Jun-14","Jul-14","Aug-14","Sep-14","Oct-14","Nov-14","Dec-14","Jan-15","Feb-15","Mar-15","Apr-15","May-15","Jun-15","Jul-15","Aug-15","Sep-15","Oct-15","Nov-15","Dec-15","Jan-16","Feb-16","Mar-16","Apr-16","May-16")
# rownames(clean.style.data) <- c("Factory A", "Factory B", "Factory C")
# clean.style.itemCols <- c(rgb(46,117,182, max=255),rgb(248,203,173, max=255),rgb(79,190,70, max=255))
# prop.stacked.data <- as.matrix(read.csv("C:/R/consumerspending.csv", header = TRUE, row.names = 1))
# prop.stacked.data.col.scheme <- MakeColorGradient(prop.stacked.data,112,48,160)
# prop.stacked.data <- AlphabeticRowNames(prop.stacked.data)
# stacked.data <- as.matrix(read.csv("C:/R/resources.csv", header = TRUE, row.names = 1))
# qColors <- c(grDevices::rgb(91, 155, 213, 255, maxColorValue = 255), # blue
#              grDevices::rgb(237, 125, 49, 255, maxColorValue = 255), # orange
#              grDevices::rgb(165, 165, 165, 255, maxColorValue = 255), # grey
#              grDevices::rgb(30, 192, 0, 255, maxColorValue = 255), # yellow
#              grDevices::rgb(68, 114, 196, 255, maxColorValue = 255), # darker blue
#              grDevices::rgb(112, 173, 71, 255, maxColorValue = 255), # green
#              grDevices::rgb(37, 94, 145, 255, maxColorValue = 255), # even darker blue
#              grDevices::rgb(158, 72, 14, 255, maxColorValue = 255), # blood
#              grDevices::rgb(99, 99, 99, 255, maxColorValue = 255), # dark grey
#              grDevices::rgb(153, 115, 0, 255, maxColorValue = 255), # brown
#              grDevices::rgb(38, 68, 120, 255, maxColorValue = 255), # very dark blue
#              grDevices::rgb(67, 104, 43, 255, maxColorValue = 255), # darker green
#              grDevices::rgb(255, 255, 255, 255, maxColorValue = 255), # black
#              grDevices::rgb(255, 35, 35, 255, maxColorValue = 255)) # red
# plotlySymbols <- plotlySymbols <- c(0,100,200,300,1,101,201,301,2,102,202,302,3,103,203,303,4,104,204,304,5,105,205,305,6,106,206,306,7,107,207,307,8,108,208,308,9,109,209,309,10,110,210,310,11,111,211,311,12,112,212,312,13,113,213,313,14,114,214,314,15,115,215,315,16,116,216,316,17,117,217,317,18,118,218,318,19,119,219,319,20,120,220,320,21,121,221,321,22,122,222,322,23,123,223,323,24,124,224,324,25,125,26,126,27,127,28,128,29,129,30,130,31,131,32,132,33,133,34,134,35,135,36,136,37,137,38,138,39,139,40,140,41,141,42,142,43,143,44,144)
#
#
# ## Layout AreaChart function calls
# layout.examples <- list("Basic style" = list(y = basic.style.data,
#                                              x = NULL,
#                                              # weights = NULL,
#                                              # subset = NULL,
#                                              transpose = TRUE,
#                                              aggregate.period = "month",
#                                              y.labels = NULL,
#                                              x.labels = NULL,
#                                              type = "Line",
#                                              title = "Line Chart - BASIC STYLE",
#                                              global.font.family = "Arial",
#                                              global.font.color = rgb(44, 44, 44, maxColorValue = 255),
#                                              global.font.size = 12,
#                                              colors = basic.style.colors,
#                                              transparency = 0.4,
#                                              chart.fill.color = rgb(255, 255, 255, maxColorValue = 255),
#                                              chart.fill.transparency = 1,
#                                              plot.fill.color = rgb(255, 255, 255, maxColorValue = 255),
#                                              plot.fill.transparency = 1,
#                                              legend.show = TRUE,
#                                              legend.fill = rgb(255, 255, 255, maxColorValue = 255),
#                                              legend.border.color = rgb(44, 44, 44, maxColorValue = 255),
#                                              legend.border.line.width = 0,
#                                              legend.font.color = rgb(44, 44, 44, maxColorValue = 255),
#                                              legend.font.family = "Arial",
#                                              legend.font.size = 12,
#                                              legend.position = "right",
#                                              legend.sort.order = "normal",
#                                              margin.top = 80,
#                                              margin.bottom = 80,
#                                              margin.left = 80,
#                                              margin.right = 80,
#                                              margin.inner.pad = 0,
#                                              y.title = "",
#                                              y.title.font.color = rgb(44, 44, 44, maxColorValue = 255),
#                                              y.title.font.family = "Arial",
#                                              y.title.font.size = 16,
#                                              y.line.width = 1,
#                                              y.line.color = rgb(0, 0, 0, maxColorValue = 255),
#                                              y.tick.marks = "",
#                                              y.tick.length = 5,
#                                              y.bounds.minimum = 0,
#                                              y.bounds.maximum = 1.01,
#                                              y.bounds.units.major = 0.1,
#                                              y.zero.line.width = 1,
#                                              y.zero.line.color = rgb(44, 44, 44, maxColorValue = 255),
#                                              y.position = "left",
#                                              y.mirror = FALSE,
#                                              y.grid.width = 1,
#                                              y.grid.color = rgb(225, 225, 225, maxColorValue = 255),
#                                              y.ticksuffix = "",
#                                              y.tickprefix = "",
#                                              y.tick.angle = 0,
#                                              y.tick.format.manual = "",
#                                              y.tick.format = c("%","2"),
#                                              y.tick.font.color = rgb(0, 0, 0, maxColorValue = 255),
#                                              y.tick.font.family = "Arial",
#                                              y.tick.font.size = 10,
#                                              y.hover.format.manual = "",
#                                              y.hover.format = c("",""),
#                                              x.title = "",
#                                              x.title.font.color = rgb(44, 44, 44, maxColorValue = 255),
#                                              x.title.font.family = "Arial",
#                                              x.title.font.size = 16,
#                                              x.line.width = 1,
#                                              x.line.color = rgb(0, 0, 0, maxColorValue = 255),
#                                              x.tick.marks = "",
#                                              x.tick.length = 5,
#                                              x.bounds.minimum = 0,
#                                              x.bounds.maximum = 1,
#                                              x.bounds.units.major = 0.2,
#                                              x.zero.line.width = 1,
#                                              x.zero.line.color = rgb(44, 44, 44, maxColorValue = 255),
#                                              x.position = "bottom",
#                                              x.mirror = FALSE,
#                                              x.grid.width = 0,
#                                              x.grid.color = rgb(225, 225, 225, maxColorValue = 255),
#                                              x.ticksuffix = "",
#                                              x.tickprefix = "",
#                                              x.tick.angle = 0,
#                                              x.tick.format.manual = "",
#                                              x.tick.format = c("",""),
#                                              x.hover.format.manual = "",
#                                              x.hover.format = c("",""),
#                                              x.tick.font.color = rgb(0, 0, 0, maxColorValue = 255),
#                                              x.tick.font.family = "Arial",
#                                              x.tick.font.size = 10,
#                                              series.marker.show = "none",
#                                              series.marker.color = qColors,
#                                              series.marker.transparency = 1,
#                                              series.marker.size = 6,
#                                              series.marker.border.width = 1,
#                                              series.marker.border.color = qColors,
#                                              series.marker.border.transparency = 1,
#                                              series.line.width = 3,
#                                              series.line.color = basic.style.line.colors,
#                                              series.line.transparency = 1,
#                                              hover.mode = "closest",
#                                              hover.include.source.value = FALSE,
#                                              hover.include.source.value.prefix = "",
#                                              hover.include.source.value.suffix = "",
#                                              hover.include.source.value.percent = FALSE,
#                                              show.modebar = FALSE),
#                         "Junk style" = list(y = junk.data,
#                                             x = NULL,
#                                             # weights = NULL,
#                                             # subset = NULL,
#                                             transpose = TRUE,
#                                             aggregate.period = "month",
#                                             y.labels = NULL,
#                                             x.labels = NULL,
#                                             type = "Line",
#                                             title = "Monthly Sales",
#                                             global.font.family = "Tahoma",
#                                             global.font.color = rgb(44, 44, 44, maxColorValue = 255),
#                                             global.font.size = 14,
#                                             colors = rgb(255, 255, 255, max=255),
#                                             transparency = 0.4,
#                                             chart.fill.color = rgb(211, 225, 254, maxColorValue = 255),
#                                             chart.fill.transparency = 1,
#                                             plot.fill.color = rgb(211, 225, 254, maxColorValue = 255),
#                                             plot.fill.transparency = 1,
#                                             legend.show = TRUE,
#                                             legend.fill = rgb(255, 255, 255, maxColorValue = 255),
#                                             legend.border.color = rgb(44, 44, 44, maxColorValue = 255),
#                                             legend.border.line.width = 0,
#                                             legend.font.color = rgb(44, 44, 44, maxColorValue = 255),
#                                             legend.font.family = "Tahoma",
#                                             legend.font.size = 12,
#                                             legend.position = "right",
#                                             legend.sort.order = "normal",
#                                             margin.top = 80,
#                                             margin.bottom = 80,
#                                             margin.left = 80,
#                                             margin.right = 80,
#                                             margin.inner.pad = 0,
#                                             y.title = "pcs",
#                                             y.title.font.color = rgb(141, 159, 183, maxColorValue = 255),
#                                             y.title.font.family = "Tahoma",
#                                             y.title.font.size = 16,
#                                             y.line.width = 1,
#                                             y.line.color = rgb(191, 191, 191, maxColorValue = 255),
#                                             y.tick.marks = "none",
#                                             y.tick.length = 0,
#                                             y.bounds.minimum = 0,
#                                             y.bounds.maximum = 50,
#                                             y.bounds.units.major = 5,
#                                             y.zero.line.width = 1,
#                                             y.zero.line.color = rgb(191, 191, 191, maxColorValue = 255),
#                                             y.position = "left",
#                                             y.mirror = FALSE,
#                                             y.grid.width = 0,
#                                             y.grid.color = rgb(225, 225, 225, maxColorValue = 255),
#                                             y.ticksuffix = "",
#                                             y.tickprefix = "",
#                                             y.tick.angle = 0,
#                                             y.tick.format.manual = "",
#                                             y.tick.format = c("",""),
#                                             y.tick.font.color = rgb(44, 44, 44, maxColorValue = 255),
#                                             y.tick.font.size = 10,
#                                             y.tick.font.family = "Tahoma",
#                                             y.hover.format.manual = "",
#                                             y.hover.format = c("",""),
#                                             x.title = "",
#                                             x.title.font.color = rgb(44, 44, 44, maxColorValue = 255),
#                                             x.title.font.family = "Tahoma",
#                                             x.title.font.size = 16,
#                                             x.line.width = 1,
#                                             x.line.color = rgb(191, 191, 191, maxColorValue = 255),
#                                             x.tick.marks = "none",
#                                             x.tick.length = 0,
#                                             x.bounds.minimum = 0,
#                                             x.bounds.maximum = 1,
#                                             x.bounds.units.major = 0.2,
#                                             x.zero.line.width = 1,
#                                             x.zero.line.color = rgb(191, 191, 191, maxColorValue = 255),
#                                             x.position = "bottom",
#                                             x.mirror = FALSE,
#                                             x.grid.width = 0,
#                                             x.grid.color = rgb(225, 225, 225, maxColorValue = 255),
#                                             x.ticksuffix = "",
#                                             x.tickprefix = "",
#                                             x.tick.angle = 0,
#                                             x.tick.format.manual = "",
#                                             x.tick.format = c("",""),
#                                             x.hover.format.manual = "",
#                                             x.hover.format = c("",""),
#                                             x.tick.font.color = rgb(44, 44, 44, maxColorValue = 255),
#                                             x.tick.font.size = 10,
#                                             x.tick.font.family = "Tahoma",
#                                             series.marker.show = c(0),
#                                             series.marker.color = junk.colors,
#                                             series.marker.transparency = 1,
#                                             series.marker.size = 4,
#                                             series.marker.border.width = 1,
#                                             series.marker.border.color = rgb(0, 0, 0, maxColorValue = 255),
#                                             series.marker.border.transparency = 1,
#                                             series.marker.text = TRUE,
#                                             series.line.width = 2,
#                                             series.line.color = junk.colors,
#                                             series.line.transparency = 1,
#                                             hover.mode = "closest",
#                                             show.modebar = FALSE),
#                         "Clean style" = list(y = clean.style.data,
#                                              x = NULL,
#                                              # weights = NULL,
#                                              # subset = NULL,
#                                              transpose = TRUE,
#                                              aggregate.period = "month",
#                                              y.labels = NULL,
#                                              x.labels = NULL,
#                                              type = "Area",
#                                              title = "Factory operating capacity",
#                                              global.font.family = "Impact",
#                                              global.font.color = rgb(44, 44, 44, maxColorValue = 255),
#                                              global.font.size = 14,
#                                              colors = clean.style.itemCols,
#                                              transparency = 0.4,
#                                              chart.fill.color = rgb(255, 255, 255, maxColorValue = 255),
#                                              chart.fill.transparency = 1,
#                                              plot.fill.color = rgb(255, 255, 255, maxColorValue = 255),
#                                              plot.fill.transparency = 1,
#                                              legend.show = TRUE,
#                                              legend.fill = rgb(255, 255, 255, maxColorValue = 255),
#                                              legend.border.color = rgb(44, 44, 44, maxColorValue = 255),
#                                              legend.border.line.width = 0,
#                                              legend.font.color = rgb(44, 44, 44, maxColorValue = 255),
#                                              legend.font.family = "Impact",
#                                              legend.font.size = 12,
#                                              legend.position = "right",
#                                              legend.sort.order = "normal",
#                                              margin.top = 80,
#                                              margin.bottom = 80,
#                                              margin.left = 80,
#                                              margin.right = 80,
#                                              margin.inner.pad = 0,
#                                              y.title = "Available production<br>capacity",
#                                              y.title.font.color = rgb(44, 44, 44, maxColorValue = 255),
#                                              y.title.font.family = "Arial",
#                                              y.title.font.size = 16,
#                                              y.line.width = 1,
#                                              y.line.color = rgb(0, 0, 0, maxColorValue = 255),
#                                              y.tick.marks = "",
#                                              y.tick.length = 5,
#                                              y.bounds.minimum = NULL,
#                                              y.bounds.maximum = NULL,
#                                              y.bounds.units.major = NULL,
#                                              y.zero.line.width = 1,
#                                              y.zero.line.color = rgb(44, 44, 44, maxColorValue = 255),
#                                              y.position = "left",
#                                              y.mirror = FALSE,
#                                              y.grid.width = 1,
#                                              y.grid.color = rgb(225, 225, 225, maxColorValue = 255),
#                                              y.ticksuffix = "",
#                                              y.tickprefix = "",
#                                              y.tick.angle = 0,
#                                              y.tick.format.manual = "",
#                                              y.tick.format = c("%",1),
#                                              y.tick.font.color = rgb(0, 0, 0, maxColorValue = 255),
#                                              y.tick.font.family = "Impact",
#                                              y.tick.font.size = 10,
#                                              y.hover.format.manual = "",
#                                              y.hover.format = c("%", 3),
#                                              x.title = "",
#                                              x.title.font.color = rgb(44, 44, 44, maxColorValue = 255),
#                                              x.title.font.family = "Arial",
#                                              x.title.font.size = 16,
#                                              x.line.width = 1,
#                                              x.line.color = rgb(0, 0, 0, maxColorValue = 255),
#                                              x.tick.marks = "",
#                                              x.tick.length = 5,
#                                              x.bounds.minimum = 0,
#                                              x.bounds.maximum = 1,
#                                              x.bounds.units.major = 0.2,
#                                              x.zero.line.width = 1,
#                                              x.zero.line.color = rgb(44, 44, 44, maxColorValue = 255),
#                                              x.position = "bottom",
#                                              x.mirror = FALSE,
#                                              x.grid.width = 0,
#                                              x.grid.color = rgb(225, 225, 225, maxColorValue = 255),
#                                              x.ticksuffix = "",
#                                              x.tickprefix = "",
#                                              x.tick.angle = -45,
#                                              x.tick.format.manual = "",
#                                              x.tick.format = c("",""),
#                                              x.hover.format.manual = "",
#                                              x.hover.format = c("",""),
#                                              x.tick.font.color = rgb(0, 0, 0, maxColorValue = 255),
#                                              x.tick.font.family = "Arial",
#                                              x.tick.font.size = 10,
#                                              series.marker.show = "none",
#                                              series.marker.color = qColors,
#                                              series.marker.transparency = 1,
#                                              series.marker.size = 6,
#                                              series.marker.border.width = 1,
#                                              series.marker.border.color = qColors,
#                                              series.marker.border.transparency = 1,
#                                              series.line.width = 0,
#                                              series.line.color = qColors,
#                                              series.line.transparency = 1,
#                                              hover.mode = "x",
#                                              hover.include.source.value = FALSE,
#                                              hover.include.source.value.prefix = "",
#                                              hover.include.source.value.suffix = "",
#                                              hover.include.source.value.percent = FALSE,
#                                              show.modebar = FALSE),
#                         "100% Stacked" = list(y = prop.stacked.data,
#                                               x = NULL,
#                                               # weights = NULL,
#                                               # subset = NULL,
#                                               transpose = TRUE,
#                                               aggregate.period = "month",
#                                               y.labels = NULL,
#                                               x.labels = NULL,
#                                               type = "100% Stacked Area",
#                                               title = "<b>Consumer Spending</b>",
#                                               global.font.family = "Arial",
#                                               global.font.color = rgb(44, 44, 44, maxColorValue = 255),
#                                               global.font.size = 14,
#                                               colors = prop.stacked.data.col.scheme,
#                                               transparency = 1,
#                                               chart.fill.color = rgb(255, 255, 255, maxColorValue = 255),
#                                               chart.fill.transparency = 1,
#                                               plot.fill.color = rgb(255, 255, 255, maxColorValue = 255),
#                                               plot.fill.transparency = 1,
#                                               legend.show = TRUE,
#                                               legend.fill = rgb(255, 255, 255, maxColorValue = 255),
#                                               legend.border.color = rgb(44, 44, 44, maxColorValue = 255),
#                                               legend.border.line.width = 0,
#                                               legend.font.color = rgb(44, 44, 44, maxColorValue = 255),
#                                               legend.font.family = "Arial",
#                                               legend.font.size = 12,
#                                               legend.position = "right",
#                                               legend.sort.order = "reverse",
#                                               margin.top = 80,
#                                               margin.bottom = 80,
#                                               margin.left = 80,
#                                               margin.right = 80,
#                                               margin.inner.pad = 0,
#                                               y.title = "",
#                                               y.title.font.color = rgb(44, 44, 44, maxColorValue = 255),
#                                               y.title.font.family = "Arial",
#                                               y.title.font.size = 16,
#                                               y.line.width = 1,
#                                               y.line.color = rgb(0, 0, 0, maxColorValue = 255),
#                                               y.tick.marks = "",
#                                               y.tick.length = 5,
#                                               y.bounds.minimum = 0,
#                                               y.bounds.maximum = 1,
#                                               y.bounds.units.major = 0.1,
#                                               y.zero.line.width = 1,
#                                               y.zero.line.color = rgb(44, 44, 44, maxColorValue = 255),
#                                               y.position = "right",
#                                               y.mirror = FALSE,
#                                               y.grid.width = 1,
#                                               y.grid.color = rgb(225, 225, 225, maxColorValue = 255),
#                                               y.ticksuffix = "",
#                                               y.tickprefix = "",
#                                               y.tick.angle = 0,
#                                               y.tick.format.manual = "",
#                                               y.tick.format = c("%",1),
#                                               y.tick.font.color = rgb(0, 0, 0, maxColorValue = 255),
#                                               y.tick.font.family = "Arial",
#                                               y.tick.font.size = 10,
#                                               y.hover.format.manual = "",
#                                               y.hover.format = c("%",3),
#                                               x.title = "",
#                                               x.title.font.color = rgb(44, 44, 44, maxColorValue = 255),
#                                               x.title.font.family = "Arial",
#                                               x.title.font.size = 16,
#                                               x.line.width = 1,
#                                               x.line.color = rgb(0, 0, 0, maxColorValue = 255),
#                                               x.tick.marks = "",
#                                               x.tick.length = 5,
#                                               x.bounds.minimum = 0,
#                                               x.bounds.maximum = 1,
#                                               x.bounds.units.major = 0.2,
#                                               x.zero.line.width = 1,
#                                               x.zero.line.color = rgb(44, 44, 44, maxColorValue = 255),
#                                               x.position = "bottom",
#                                               x.mirror = FALSE,
#                                               x.grid.width = 0,
#                                               x.grid.color = rgb(225, 225, 225, maxColorValue = 255),
#                                               x.ticksuffix = "",
#                                               x.tickprefix = "",
#                                               x.tick.angle = 0,
#                                               x.tick.format.manual = "",
#                                               x.tick.format = c("",""),
#                                               x.hover.format.manual = "",
#                                               x.hover.format = c("",""),
#                                               x.tick.font.color = rgb(0, 0, 0, maxColorValue = 255),
#                                               x.tick.font.family = "Arial",
#                                               x.tick.font.size = 10,
#                                               series.marker.show = "none",
#                                               series.marker.color = qColors,
#                                               series.marker.transparency = 1,
#                                               series.marker.size = 6,
#                                               series.marker.border.width = 1,
#                                               series.marker.border.color = qColors,
#                                               series.marker.border.transparency = 1,
#                                               series.line.width = 0,
#                                               series.line.color = qColors,
#                                               series.line.transparency = 1,
#                                               hover.mode = "closest",
#                                               hover.include.source.value = TRUE,
#                                               hover.include.source.value.prefix = "$",
#                                               hover.include.source.value.suffix = "",
#                                               hover.include.source.value.percent = FALSE,
#                                               show.modebar = FALSE),
#                         "Stacked" = list(y = stacked.data,
#                                          x = NULL,
#                                          # weights = NULL,
#                                          # subset = NULL,
#                                          transpose = TRUE,
#                                          aggregate.period = "month",
#                                          y.labels = NULL,
#                                          x.labels = NULL,
#                                          type = "Stacked Area",
#                                          title = "Resources by company size",
#                                          global.font.family = "Arial",
#                                          global.font.color = rgb(44, 44, 44, maxColorValue = 255),
#                                          global.font.size = 14,
#                                          colors = qColors,
#                                          transparency = 1,
#                                          chart.fill.color = rgb(255, 255, 255, maxColorValue = 255),
#                                          chart.fill.transparency = 1,
#                                          plot.fill.color = rgb(255, 255, 255, maxColorValue = 255),
#                                          plot.fill.transparency = 1,
#                                          legend.show = TRUE,
#                                          legend.fill = rgb(255, 255, 255, maxColorValue = 255),
#                                          legend.border.color = rgb(44, 44, 44, maxColorValue = 255),
#                                          legend.border.line.width = 0,
#                                          legend.font.color = rgb(44, 44, 44, maxColorValue = 255),
#                                          legend.font.family = "Arial",
#                                          legend.font.size = 12,
#                                          legend.position = "right",
#                                          legend.sort.order = "reverse",
#                                          margin.top = 80,
#                                          margin.bottom = 80,
#                                          margin.left = 80,
#                                          margin.right = 80,
#                                          margin.inner.pad = 0,
#                                          y.title = "",
#                                          y.title.font.color = rgb(44, 44, 44, maxColorValue = 255),
#                                          y.title.font.family = "Arial",
#                                          y.title.font.size = 16,
#                                          y.line.width = 0,
#                                          y.line.color = rgb(0, 0, 0, maxColorValue = 255),
#                                          y.tick.marks = "",
#                                          y.tick.length = 5,
#                                          y.bounds.minimum = NULL,
#                                          y.bounds.maximum = NULL,
#                                          y.bounds.units.major = NULL,
#                                          y.zero.line.width = 0,
#                                          y.zero.line.color = rgb(44, 44, 44, maxColorValue = 255),
#                                          y.position = "left",
#                                          y.mirror = FALSE,
#                                          y.grid.width = 0,
#                                          y.grid.color = rgb(225, 225, 225, maxColorValue = 255),
#                                          y.ticksuffix = "",
#                                          y.tickprefix = "",
#                                          y.tick.angle = 0,
#                                          y.tick.format.manual = "",
#                                          y.tick.format = c("n",1),
#                                          y.tick.font.color = rgb(0, 0, 0, maxColorValue = 255),
#                                          y.tick.font.family = "Arial",
#                                          y.tick.font.size = 10,
#                                          y.hover.format.manual = "",
#                                          y.hover.format = c("n",2),
#                                          x.title = "Number of staff",
#                                          x.title.font.color = rgb(44, 44, 44, maxColorValue = 255),
#                                          x.title.font.family = "Arial",
#                                          x.title.font.size = 16,
#                                          x.line.width = 1,
#                                          x.line.color = rgb(0, 0, 0, maxColorValue = 255),
#                                          x.tick.marks = "",
#                                          x.tick.length = 5,
#                                          x.bounds.minimum = 0,
#                                          x.bounds.maximum = 1,
#                                          x.bounds.units.major = 0.2,
#                                          x.zero.line.width = 1,
#                                          x.zero.line.color = rgb(44, 44, 44, maxColorValue = 255),
#                                          x.position = "bottom",
#                                          x.mirror = FALSE,
#                                          x.grid.width = 0,
#                                          x.grid.color = rgb(225, 225, 225, maxColorValue = 255),
#                                          x.ticksuffix = "",
#                                          x.tickprefix = "",
#                                          x.tick.angle = 0,
#                                          x.tick.format.manual = "",
#                                          x.tick.format = c("",""),
#                                          x.hover.format.manual = "",
#                                          x.hover.format = c("",""),
#                                          x.tick.font.color = rgb(0, 0, 0, maxColorValue = 255),
#                                          x.tick.font.family = "Arial",
#                                          x.tick.font.size = 10,
#                                          series.marker.show = "none",
#                                          series.marker.color = qColors,
#                                          series.marker.transparency = 1,
#                                          series.marker.size = 6,
#                                          series.marker.border.width = 1,
#                                          series.marker.border.color = qColors,
#                                          series.marker.border.transparency = 1,
#                                          series.line.width = 0,
#                                          series.line.color = qColors,
#                                          series.line.transparency = 1,
#                                          hover.mode = "x",
#                                          hover.include.source.value = TRUE,
#                                          hover.include.source.value.prefix = "Staff:",
#                                          hover.include.source.value.suffix = "",
#                                          hover.include.source.value.percent = FALSE,
#                                          show.modebar = FALSE)
# )
#
# for (i in 1:length(layout.examples))
# {
#     print(AreaChart(y = layout.examples[[i]]$y,
#                     x  = layout.examples[[i]]$x,
#                     # weights
#                     # subset
#                     transpose  = layout.examples[[i]]$transpose ,
#                     aggregate.period  = layout.examples[[i]]$aggregate.period ,
#                     y.labels  = layout.examples[[i]]$y.labels ,
#                     x.labels  = layout.examples[[i]]$x.labels ,
#                     type  = layout.examples[[i]]$type ,
#                     title  = layout.examples[[i]]$title ,
#                     global.font.family = layout.examples[[i]]$global.font.family,
#                     global.font.color = layout.examples[[i]]$global.font.color,
#                     global.font.size = layout.examples[[i]]$global.font.size,
#                     colors  = layout.examples[[i]]$colors ,
#                     transparency  = layout.examples[[i]]$transparency ,
#                     chart.fill.color  = layout.examples[[i]]$chart.fill.color ,
#                     chart.fill.transparency  = layout.examples[[i]]$chart.fill.transparency ,
#                     plot.fill.color  = layout.examples[[i]]$plot.fill.color ,
#                     plot.fill.transparency  = layout.examples[[i]]$plot.fill.transparency ,
#                     legend.show  = layout.examples[[i]]$legend.show ,
#                     legend.fill  = layout.examples[[i]]$legend.fill ,
#                     legend.border.color  = layout.examples[[i]]$legend.border.color ,
#                     legend.border.line.width  = layout.examples[[i]]$legend.border.line.width ,
#                     legend.font.color  = layout.examples[[i]]$legend.font.color ,
#                     legend.font.family  = layout.examples[[i]]$legend.font.family ,
#                     legend.font.size  = layout.examples[[i]]$legend.font.size ,
#                     legend.position  = layout.examples[[i]]$legend.position ,
#                     legend.sort.order  = layout.examples[[i]]$legend.sort.order ,
#                     margin.top  = layout.examples[[i]]$margin.top ,
#                     margin.bottom  = layout.examples[[i]]$margin.bottom ,
#                     margin.left  = layout.examples[[i]]$margin.left ,
#                     margin.right  = layout.examples[[i]]$margin.right ,
#                     margin.inner.pad  = layout.examples[[i]]$margin.inner.pad ,
#                     y.title  = layout.examples[[i]]$y.title ,
#                     y.title.font.color  = layout.examples[[i]]$y.title.font.color ,
#                     y.title.font.family  = layout.examples[[i]]$y.title.font.family ,
#                     y.title.font.size  = layout.examples[[i]]$y.title.font.size ,
#                     y.line.width  = layout.examples[[i]]$y.line.width ,
#                     y.line.color  = layout.examples[[i]]$y.line.color ,
#                     y.tick.marks  = layout.examples[[i]]$y.tick.marks ,
#                     y.tick.length  = layout.examples[[i]]$y.tick.length ,
#                     y.bounds.minimum  = layout.examples[[i]]$y.bounds.minimum ,
#                     y.bounds.maximum  = layout.examples[[i]]$y.bounds.maximum ,
#                     y.bounds.units.major  = layout.examples[[i]]$y.bounds.units.major ,
#                     y.zero.line.width  = layout.examples[[i]]$y.zero.line.width ,
#                     y.zero.line.color  = layout.examples[[i]]$y.zero.line.color ,
#                     y.position  = layout.examples[[i]]$y.position ,
#                     y.mirror  = layout.examples[[i]]$y.mirror ,
#                     y.grid.width  = layout.examples[[i]]$y.grid.width ,
#                     y.grid.color  = layout.examples[[i]]$y.grid.color ,
#                     y.ticksuffix  = layout.examples[[i]]$y.ticksuffix ,
#                     y.tickprefix  = layout.examples[[i]]$y.tickprefix ,
#                     y.tick.angle  = layout.examples[[i]]$y.tick.angle ,
#                     y.tick.format.manual  = layout.examples[[i]]$y.tick.format.manual ,
#                     y.tick.format  = layout.examples[[i]]$y.tick.format ,
#                     y.tick.font.color  = layout.examples[[i]]$y.tick.font.color ,
#                     y.tick.font.family  = layout.examples[[i]]$y.tick.font.family ,
#                     y.tick.font.size  = layout.examples[[i]]$y.tick.font.size ,
#                     y.hover.format.manual  = layout.examples[[i]]$y.hover.format.manual ,
#                     y.hover.format  = layout.examples[[i]]$y.hover.format ,
#                     x.title  = layout.examples[[i]]$x.title ,
#                     x.title.font.color  = layout.examples[[i]]$x.title.font.color ,
#                     x.title.font.family  = layout.examples[[i]]$x.title.font.family ,
#                     x.title.font.size  = layout.examples[[i]]$x.title.font.size ,
#                     x.line.width  = layout.examples[[i]]$x.line.width ,
#                     x.line.color  = layout.examples[[i]]$x.line.color ,
#                     x.tick.marks  = layout.examples[[i]]$x.tick.marks ,
#                     x.tick.length  = layout.examples[[i]]$x.tick.length ,
#                     x.bounds.minimum  = layout.examples[[i]]$x.bounds.minimum ,
#                     x.bounds.maximum  = layout.examples[[i]]$x.bounds.maximum ,
#                     x.bounds.units.major  = layout.examples[[i]]$x.bounds.units.major ,
#                     x.zero.line.width  = layout.examples[[i]]$x.zero.line.width ,
#                     x.zero.line.color  = layout.examples[[i]]$x.zero.line.color ,
#                     x.position  = layout.examples[[i]]$x.position ,
#                     x.mirror  = layout.examples[[i]]$x.mirror ,
#                     x.grid.width  = layout.examples[[i]]$x.grid.width ,
#                     x.grid.color  = layout.examples[[i]]$x.grid.color ,
#                     x.ticksuffix  = layout.examples[[i]]$x.ticksuffix ,
#                     x.tickprefix  = layout.examples[[i]]$x.tickprefix ,
#                     x.tick.angle  = layout.examples[[i]]$x.tick.angle ,
#                     x.tick.format.manual  = layout.examples[[i]]$x.tick.format.manual ,
#                     x.tick.format  = layout.examples[[i]]$x.tick.format ,
#                     x.hover.format.manual  = layout.examples[[i]]$x.hover.format.manual ,
#                     x.hover.format  = layout.examples[[i]]$x.hover.format ,
#                     x.tick.font.color  = layout.examples[[i]]$x.tick.font.color ,
#                     x.tick.font.family  = layout.examples[[i]]$x.tick.font.family ,
#                     x.tick.font.size  = layout.examples[[i]]$x.tick.font.size ,
#                     series.marker.show  = layout.examples[[i]]$series.marker.show ,
#                     series.marker.color  = layout.examples[[i]]$series.marker.color ,
#                     series.marker.transparency  = layout.examples[[i]]$series.marker.transparency ,
#                     series.marker.size  = layout.examples[[i]]$series.marker.size ,
#                     series.marker.border.width  = layout.examples[[i]]$series.marker.border.width ,
#                     series.marker.border.color  = layout.examples[[i]]$series.marker.border.color ,
#                     series.marker.border.transparency  = layout.examples[[i]]$series.marker.border.transparency ,
#                     series.line.width  = layout.examples[[i]]$series.line.width ,
#                     series.line.color  = layout.examples[[i]]$series.line.color ,
#                     series.line.transparency  = layout.examples[[i]]$series.line.transparency ,
#                     hover.mode  = layout.examples[[i]]$hover.mode ,
#                     hover.include.source.value = layout.examples[[i]]$hover.include.source.value,
#                     hover.include.source.value.prefix = layout.examples[[i]]$hover.include.source.value.prefix,
#                     hover.include.source.value.suffix = layout.examples[[i]]$hover.include.source.value.suffix,
#                     hover.include.source.value.percent = layout.examples[[i]]$hover.include.source.value.percent,
#                     show.modebar  = layout.examples[[i]]$show.modebar)
#     )
#
#
#     # cat(paste("Press [enter] to continue (test ", i, "/", length(layout.examples), ").", sep = ""))
#     # line <- readline()
# }
